#!/bin/bash
# Copyright 2009-2016 Victor Boyko, Tashkent, Uzbekistan <bvoid(at)yandex.ru>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  THIS SOFTWARE FOR NON COMMERCIAL USING ONLY.

b=`basename $0`
e='echo -e'

func_calls () {
  if [ ! -r /etc/i.d/${1} ]; then
    $e " \033[1;31m*\033[0;0m Service /etc/i.d/${1} not found!"
    exit 1
  fi
  /etc/i.d/$@
}

all_serv_stat () {
  for S in /etc/i.d/*[!~] ; do
    if [ -x $S ] ; then
      S=`basename $S`
      if [ ! `pidof -s $S` ]; then
        $e "$S\r\t\t :\033[1;31mdown\033[0;0m"
      else
        $e "$S\r\t\t :\033[1;32mup\033[0;0m"
      fi
    fi
  done
}

if [ ! $1 ]; then
  $e " Usage: $b {service_name} {service_options ...} e.g. \"$b openvpn start client0\""
  exit 1
fi

case "$1" in
  all)
    case "$2" in
      up) all_serv_stat |grep ";32mup"
      ;;
      down) all_serv_stat |grep ";31mdown"
      ;;
      *) all_serv_stat
      ;;
    esac
  ;;
  *) func_calls $@
  ;;
esac
