#!/bin/bash
PATH=/bin:/sbin:/usr/sbin:/usr/bin
e="echo -e"
m="mount"
tmpm="${m} -nt tmpfs tmpfs"

s_vfs() {
  $m -no re${m},ro /
  $m -no nosuid,noexec,nodev -t proc proc /proc
  $m -no nosuid,noexec,nodev -t sysfs sysfs /sys
    mkdir -p /dev/{pts,shm} &>/dev/null 
  $m -no gid=5,mode=620 -t devpts devpts /dev/pts
  $tmpm -o mode=1777 /dev/shm
  $m -t cgroup cgroup_all /sys/fs/cgroup
}

s_tmpfs() {
  $tmpm -o mode=1755,size=5% /run
  $tmpm -o mode=1777,size=5% /var/lock
  $tmpm -o mode=1777,size=50% /tmp
  $tmpm -o mode=1777,size=59% /ram
    mkdir -p /tmp/.{ICE,X11}-unix
    chmod 1777 /tmp/.{ICE,X11}-unix
}

s_sysfs() {
  $e 32,196,0,224,0,196,0,224,128,196,0,224,0,196,0,255 \
        > /sys/module/vt/parameters/default_red
  $e 32,0,196,128,0,0,196,224,128,0,196,128,0,0,196,255 \
        > /sys/module/vt/parameters/default_grn
  $e 32,0,0,78,196,196,224,224,128,0,0,78,196,196,224,255 \
        > /sys/module/vt/parameters/default_blu
  ### hmmm... bright!
  #$e 64,224,96,224,128,224,96,224,128,224,96,224,128,224,96,255 \
  #     >/sys/module/vt/parameters/default_red
  #$e 64,96,192,128,128,128,192,224,128,96,192,128,128,128,192,255 \
  #     >/sys/module/vt/parameters/default_grn
  #$e 64,96,128,96,224,224,224,224,128,96,128,96,224,224,224,255 \
  #     >/sys/module/vt/parameters/default_blu
  $e -ne "\033]R" > /dev/tty1
  $e 4 > /sys/class/backlight/thinkpad_screen/brightness
  $e low > /sys/class/drm/card0/device/power_dpm_force_performance_level
  $e battery > /sys/class/drm/card0/device/power_dpm_state
  #$e low > /sys/class/drm/card0/device/power_profile
  $e 1 > /proc/sys/vm/oom_kill_allocating_task
  $e 2 > /proc/sys/vm/overcommit_memory
  $e 100 > /proc/sys/vm/overcommit_ratio
  $e 500 > /proc/sys/vm/dirty_expire_centisecs
  $e 100 > /proc/sys/vm/swappiness
}

s_fsck() {
  fsck -AyC
  if [ $? -gt 1 ]; then
     $e "\033[0K\n\033[1;31m<!>\033[0;0m  ERROR\n"
     $e "Your filesystem has been severely damaged. You can probably"
     $e "correct this problem by running e2fsck manually (eg."
     $e "with the -v and -y options). After you logout,"
     $e "the system will reboot\033[0K\n"
     PS1="(Repair filesystem)# "
     export PS1
     sulogin -t10
     s_halt
     $e "\033[0K\n\033[1;33m  ( ^_^)  Please stand by while rebooting\033[0K\n"
     reboot -dfi
  fi
}

s_rw() {
  $m -no re${m},rw /
}

s_amnt() {
  $m -naFt nonfs,nosmbfs,nocifs
  swapon /dev/sda1
  #swapon -a
}

s_udev() {
  $e "" > /proc/sys/kernel/hotplug
  udevd --daemon
  udevadm trigger --action=add --type=subsystems
  udevadm trigger --action=add --type=devices
  udevadm settle
}

s_srv() {
  syslogd -m0
  #klogd
  acpid -nl
  #fcron
}

s_cons() {
  for tty in /dev/tty{1,2}; do
    setfont ter-v24b -C $tty
  done
  loadkeys ruwin_ct_sh-UTF-8
  $e 0 > /sys/class/graphics/fbcon/cursor_blink
}

s_lonet() {
  ip link set lo up
  ip addr add 127.0.0.1/8 label lo dev lo
  #hostname -F /etc/hostname
}

s_net() {
  ip link set eth0 up
  ip a a 192.168.8.13/24 dev eth0
  #ip a a 192.168.1.13/24 dev eth0
  #ip a a 10.0.0.13/24 dev eth0
  #ip r a default via 192.168.8.8 dev eth0
  dnsmasq
  /usr/sbin/sshd -f /etc/ssh/sshd_config
  eval "$(ssh-agent -s)"
  $e 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
  $e 0 > /proc/sys/net/ipv4/conf/all/accept_source_route
  $e 0 > /proc/sys/net/ipv4/conf/default/accept_source_route
  $e 1 > /proc/sys/net/ipv4/tcp_syncookies
  $e 0 > /proc/sys/net/ipv4/conf/default/accept_redirects
  $e 0 > /proc/sys/net/ipv4/conf/all/send_redirects
  $e 0 > /proc/sys/net/ipv4/conf/default/send_redirects
  $e 1 > /proc/sys/net/ipv4/conf/all/rp_filter
  $e 1 > /proc/sys/net/ipv4/conf/default/rp_filter
  $e 1 > /proc/sys/net/ipv4/conf/all/log_martians
  $e 1 > /proc/sys/net/ipv4/conf/default/log_martians
  $e 2 > /proc/sys/net/ipv4/ip_dynaddr
  $e 0 > /proc/sys/net/ipv4/tcp_ecn
}

s_local() {
  /usr/sbin/gpm -m /dev/input/mice -t imps2 -2 \
      -l "a-zA-Z0-9_.:~\-+=$%@&\?/\300-\326\330-\366\370-\377"
  #hdparm -B254 -S0 /dev/sda
  #fbset -s > /etc/fb.modes
  alsactl restore
}

s_halt() {
  nbd_u${m} &>/dev/null

  fuser -av -m / &> /var/log/fuser_1.log
  $e "\r\033[0K\033[1;33m *\033[0;0m Sending all processes the TERM signal"
  killall5 -15 &>/dev/null

  #TODO: replace this ugly variant with normal (lsof?..)
  if [[ `fuser -av -m / 2>&1 |grep ". Frc"` ]]; then
    for x in `seq 10`; do
      if [[ `fuser -av -m / 2>&1 |grep ". Frc"` ]]; then
        $e -n "\033[0K ."
        sleep 0.5
      fi
    done
  $e "\r\033[0K\033[1;31m *\033[0;0m Sending all processes the KILL signal"
  killall5 -9 &>/dev/null
  fi

  $e "\r\033[0K\033[1;33m *\033[0;0m Flushing filesystem buffers"
  sync

  for logf in /var/log/*log ; do
    if [ $(stat -c%s $logf) -ge 10000000 ]; then
    $e "\033[0K\033[1;33m *\033[0;0m Rotate logs"
    cat $logf | gzip -9 > "$logf"_`date +%F`.gz || break
    rm -v $logf
    fi
  done

  telinit u
  fuser -av -m / &> /var/log/fuser_0.log

  $e "\r\033[0K\033[1;33m *\033[0;0m Turn swap off"
  swapoff -a
  sync

  $e "\033[0K\033[1;33m *\033[0;0m Re${m}ing root filesystem read-only"
  ${m} -no re${m},ro /

  $e "\033[0K\033[1;33m *\033[0;0m Un${m}ing network / local filesystems"
  u${m} -a &>/dev/null
}

failexit() {
  $e " [E] Fail! Exit"
  exit
}

case "$1" in
  S)
    s_vfs &
    s_tmpfs &
    s_fsck
    ( s_sysfs &
      s_rw &
      s_udev &
      s_amnt
      s_srv 
    )&>/dev/null &
  ;;
  2)
    ( s_cons &
      s_lonet &
      #s_perm
      s_local
    )&>/dev/null &
  ;;
  3|4|5)
    ( s_cons &
      s_lonet &
      s_net
      #s_perm
      s_local
    )&>/dev/null &
  ;;
  6)
    s_halt
    $e "\n\033[1;33m  ( ^_^)  Please stand by while rebooting"
    reboot -dfi
  ;;
  1)
    $e "\033[0K\n\033[1;31m <!>\033[0;0m  Going to Single User Mode..."
    s_halt
    s_vfs
    s_tmpfs
    s_cons
    s_udev
    $e "\n\nAfter you logout, the system will reboot\n"
    PS1="(Single User Mode)# "
    export PS1
    sulogin -t10
    s_halt
    $e "\033[0K\n\033[1;33m  ( ^_^)  Please stand by while rebooting\n"
    reboot -dfi
  ;;
  0)
    s_halt
    $e "\033[0K\n\033[1;34m  (-_- )  Bye...\n"
    halt -dfip
  ;;
  *)
    $e "\033[0K\nUsage ${0} {S 1 2 3 4 5 6 0}\n"
    exit 1
  ;;
esac
