#!/bin/bash
PATH=/bin:/sbin:/usr/sbin:/usr/bin
e="echo -e"
b=`basename $0`

if [ $2 ]  && [ ! -r /etc/ppp/peers/$2 ]; then
  $e "\033[1;31m *\033[0;0m Config file \"/etc/ppp/peers/$2\" not read! Exit"
  exit 1
fi

check_stat () {
if [ ! $2 ]; then
  p="$b call"
  c=
  prog_stat=`pgrep -fo "$p"`
else
  p="$b call $2"
  c="$2"
  prog_stat=`pgrep -fox "$p"`
fi
}

fail_exit () {
  $e "\033[1;31m * arghhhh!\033[0;0m something wrong"
  exit 1
}

start () {
check_stat $@
  if [ ! $c ]; then
    $e "\033[1;31m *\033[0;0m No config file set! Exit"
    exit 1
  fi
  if [ ! $prog_stat ]; then
    $p ||fail_exit
    $e "\033[1;33m *\033[0;0m $b starting $c..."
    sleep 1
    status $@
  else
    $e "\033[1;33m *\033[0;0m $b already run:\t `pgrep -d, -fx "$p"`"
  fi
}

stop () {
check_stat $@
  if [ ! $c ]; then
    if [ $prog_stat ]; then
      $e -n "\033[1;33m *\033[0;0m $b stopping..."
      kill `pgrep -d" " -f "$p"` ||fail_exit
      sleep 1
      $e "\033[1;32m done\033[0;0m"
    else
      $e "\033[1;31m *\033[0;0m $b not run!"
    fi
  else
    if [ $prog_stat ]; then
      $e -n "\033[1;33m *\033[0;0m $b stopping $c..."
      pkill -fox "$p" ||fail_exit
      sleep 1
      $e "\033[1;32m done\033[0;0m"
    else
      $e "\033[1;31m *\033[0;0m $b not run $c!"
    fi
  fi
}

reload () {
check_stat $@
  if [ ! $c ]; then
    if [ $prog_stat ]; then
      $e -n "\033[1;33m *\033[0;0m $b reloading configs..."
      kill -HUP `pgrep -d" " -f "$p"` ||fail_exit
      sleep 1
      $e "\033[1;32m done\033[0;0m"
      status $@
    else
      $e "\033[1;31m *\033[0;0m $b not run!"
    fi
  else
    if [ $prog_stat ]; then
      $e -n "\033[1;33m *\033[0;0m $b reloading $c config..."
      pkill -HUP -fox "$p" ||fail_exit
      sleep 1
      $e "\033[1;32m done\033[0;0m"
      status $@
    else
      $e "\033[1;31m *\033[0;0m $b not run $c!"
    fi
  fi
}

status () {
check_stat $@
  if [ $prog_stat ]; then
    $e "\033[1;32m *\033[0;0m $b run:\t `pgrep -d, -f "$p"`"
  else
    if [ ! $c ]; then
      $e "\033[1;31m *\033[0;0m $b not run!"
    else
      $e "\033[1;31m *\033[0;0m $b not run $c!"
    fi
  fi
}

case "$1" in
  start) start $@
  ;;
  stop) stop $@
  ;;
  restart) stop $@ ; start $@
  ;;
  reload) reload $@
  ;;
  status|stat) status $@
  ;;
  *) $e " \033[1;33mUsage:\033[0;0m services $b {start stop restart reload status} {config file in /etc/ppp/peers/}
       (e.g. \"services $b start pppoe\")"
  exit 1
  ;;
esac
