#!/bin/bash
PATH=/bin:/sbin:/usr/sbin:/usr/bin
e="echo -e"
b=`basename $0`

check_stat () {
if [ `pidof -s "$b"` ]; then
  prog_stat=`pidof -s "$b"`
else
  prog_stat=
fi
}

fail_exit () {
  $e "\033[1;31m * arghhhh!\033[0;0m something wrong"
  exit 1
}

start () {
  check_stat
  if [ ! $prog_stat ]; then
    $b --daemon ||fail_exit
    $e "\033[1;33m *\033[0;0m $b starting..."
    udevadm trigger --action=add --type=subsystems 2>/dev/null<1
    udevadm trigger --action=add --type=devices 2>/dev/null<1
    udevadm settle
    sleep 1
    status
  else
    $e "\033[1;33m *\033[0;0m $b already run:\t `pidof "$b"`"
  fi
}

stop () {
  check_stat
  if [ $prog_stat ]; then
    $e -n "\033[1;31m *\033[0;0m $b stopping..."
    kill `pidof "$b"` ||fail_exit
    sleep 1
    $e "\033[1;32m done\033[0;0m"
  else
    $e "\033[1;31m *\033[0;0m $b not run!"
  fi
}

reload () {
  check_stat
  if [ $prog_stat ]; then
    $e -n "\033[1;33m *\033[0;0m $b reloading configs..."
    kill -HUP `pidof "$b"` ||fail_exit
    sleep 1
    $e "\033[1;32m done\033[0;0m"
    status
  else
    $e "\033[1;31m *\033[0;0m $b not run!"
  fi
}

status () {
  check_stat
  if [ $prog_stat ]; then
    $e "\033[1;32m *\033[0;0m $b run:\t `pidof "$b"`"
  else
    $e "\033[1;31m *\033[0;0m $b not run!"
  fi
}

case "$1" in
  start) start
  ;;
  stop) stop
  ;;
  restart)
  stop ; start
  ;;
  reload) reload
  ;;
  status|stat) status
  ;;
  *) $e "\033[1;33mUsage:\033[0;0m services $b {start stop restart reload status} (e.g. \"services $b stat\")"
  exit 1
  ;;
esac
